### ISSUE TITLE
mob crashes

### ISSUE THREAD

**Issue by cmhobbs** [kaadmy/pixture#38] opened 2017-03-25 17:50 UTC
On Minetest 0.4.15 (built from source) on Ubuntu Xenial, using the Pixture code from master.

When I walk on or near running water, the game eventually crashes with:

````Lua: Invalid float vector dimension range 'x' (expected -2.14748e+06 < x < 2.14748e+06 got -nan).````

**Comment by cmhobbs** [comment] 2017-03-25 17:53
I created a new world and it seems to happen even when water isn't present.

**Comment by kaadmy** [comment] 2017-03-25 17:56
I haven't kept track of anything with Minetest or Pixture for months now, might have been a change in Minetest 0.4.15 or something.

**Comment by cmhobbs** [comment] 2017-03-25 18:38
Good to know.  Water may be a red herring as it seems to occur somewhat randomly.  I've been trying to reproduce the issue but can't come up with the proper conditions.

What version do you recommend for the subgame?

**Comment by kaadmy** [comment] 2017-03-25 19:44
I used 0.4.13 for development, but I think 0.4.14 should also work.
I also noticed another bug with opening the achievements tab crashes... possibly related to changed inventory handling in 0.4.15?

**Comment by kaadmy** [comment] 2017-05-10 16:42
Interesting, this isn't related to water at all....
` ERROR[Main]: ServerError: Lua: Runtime error from mod 'mobs' in callback luaentity_Step(): Invalid float vector dimension range 'x' (expected -2.14748e+06 < x < 2.14748e+06 got -nan).`
It's a bug in mobs :D

**Comment by Wuzzy2** [comment] 2017-05-12 13:50
`-nan`? This looks like a division got seriously wrong (like `0/0`).

**Comment by kaadmy** [comment] 2017-05-12 13:54
Yeah, that's also the exact return value from `getyaw`, I can't reliably reproduce it but it happens pretty reliably if I let the game sit for a few minutes since mobs eventually spawn and crash.

**Comment by kaadmy** [comment] 2017-05-12 15:56
For now I'll just add a shim to ignore `nan` values until I find a legitimate fix since this is a major bug that doesn't *seem* to have a known way to trigger it.

**Comment by kaadmy** [comment] 2017-05-12 16:03
Shim added in dffc4b97dba5e8384ca880e91c7a4de5e042025b
The crash shouldn't happen anymore, but this will have to be fixed in more detail later.

**Closed as completed by kaadmy** 2017-05-12 16:03 UTC
Labels: shim
